import React from 'react';
import {SafeAreaView} from 'react-native';
import CardNotification from './src/components/cardNotification';

function App(): React.ReactElement {
  return (
    <SafeAreaView style={{flex: 1, backgroundColor: '#eee', padding: 8}}>
      <CardNotification
        title="TEST PER IL TITOLO"
        description="TEST PERE LA DESCRIZIONE QUACLSOA TIPO LOREM IPSUM O ROBE DEL GENRE NON NE SO ESATTAMENTE MOLTO AR IGUARDO MA STO CERACNDO D I IMPARARE E STO PURE SCRIVEND DI MREDA PERCHE ' LO STO ACENDO TROPPO VELOCEMENTE WOW QUANTE NE STO MANCANDO PORCODDIO SE SONO MESSO MALE MI RICRODAVO DI ESSERE CAPACE A SCRIVERE VELOCEMENTE DI PRIMO GETTO MA SIVEDE CHE NON SONO PIU SOGGETTO ALLEEMOZIONI QUINDI CICCO DI CONTINUO"
        orario="15:30"
      />
      <CardNotification
        title="TEST PER IL TITOLO"
        description="TEST PERE LA DESCRIZIONE QUACLSOA TIPO LOREM IPSUM O ROBE DEL GENRE NON NE SO ESATTAMENTE MOLTO AR IGUARDO MA STO CERACNDO D I IMPARARE E STO PURE SCRIVEND DI MREDA PERCHE ' LO STO ACENDO TROPPO VELOCEMENTE WOW QUANTE NE STO MANCANDO PORCODDIO SE SONO MESSO MALE MI RICRODAVO DI ESSERE CAPACE A SCRIVERE VELOCEMENTE DI PRIMO GETTO MA SIVEDE CHE NON SONO PIU SOGGETTO ALLEEMOZIONI QUINDI CICCO DI CONTINUO"
        orario="15:30"
      />
      <CardNotification
        title="TEST PER IL TITOLO"
        description="TEST PERE LA DESCRIZIONE QUACLSOA TIPO LOREM IPSUM O ROBE DEL GENRE NON NE SO ESATTAMENTE MOLTO AR IGUARDO MA STO CERACNDO D I IMPARARE E STO PURE SCRIVEND DI MREDA PERCHE ' LO STO ACENDO TROPPO VELOCEMENTE WOW QUANTE NE STO MANCANDO PORCODDIO SE SONO MESSO MALE MI RICRODAVO DI ESSERE CAPACE A SCRIVERE VELOCEMENTE DI PRIMO GETTO MA SIVEDE CHE NON SONO PIU SOGGETTO ALLEEMOZIONI QUINDI CICCO DI CONTINUO"
        orario="15:30"
      />
    </SafeAreaView>
  );
}

export default App;
